# Generated by Django 3.0.8 on 2020-08-02 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gametype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
