# Generated by Django 3.0.8 on 2020-08-05 22:12

import chess.chess_configurations
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0002_auto_20200802_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=chess.chess_configurations.get_standard_chess_pieces),
        ),
    ]
