# Generated by Django 3.0.8 on 2020-08-06 23:08

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chess', '0003_auto_20200805_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField()),
                ('current_board', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'turn',
                    models.CharField(
                        choices=[('b', 'Black'), ('w', 'White')],
                        default='w',
                        max_length=1,
                    ),
                ),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'player1',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='games_player1',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'player2',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='games_player2',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
