# Generated by Django 3.0.8 on 2020-08-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0004_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_board',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
    ]
