# Generated by Django 3.1 on 2020-08-11 22:22

from django.db import migrations, models

import chess.chess_configurations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0006_auto_20200809_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.JSONField(
                default=chess.chess_configurations.get_standard_chess_pieces
            ),
        ),
    ]
