# Generated by Django 3.1 on 2020-08-14 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import chess.chess_configurations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0007_auto_20200811_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=chess.chess_configurations.get_standard_chess_pieces
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
