# Generated by Django 3.1.2 on 2020-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0011_gametype_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='free_play',
            field=models.BooleanField(default=True),
        ),
    ]
